name: sandboxies
description: "This is a Flutter monorepo. Collection of multiple Flutter apps and shared packages"
publish_to: "none"

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

workspace:
  # Projects
  - apps/starty
  # Packages
  - packages/app_shared

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # dart
  async: ^2.12.0
  collection: ^1.19.1
  intl: ^0.20.2
  meta: ^1.16.0
  # Plugins and native
  flutter_displaymode: 0.6.0
  window_manager: ^0.5.0
  # Presentation and ui
  material_symbols_icons: ^4.2815.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15

flutter:
  generate: true

flutter_intl:
  enabled: true
  output_dir: /
  arb_dir: /
