name: sandboxies
description: "This is a Flutter monorepo. Collection of multiple Flutter apps and shared packages"
publish_to: "none"

environment:
  sdk: ^3.11.0

workspace:
  # Applications.
  - apps/sandboxy

  # Packages.
  - packages/app_shared

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dart.
  async: ^2.13.0
  collection: ^1.19.1
  intl: ^0.20.2
  meta: ^1.17.0
  # Internal.
  l: 5.0.1
  # Platform-dependant (Plugins).
  flutter_displaymode: 0.7.0
  window_manager: 0.5.1

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true

flutter_intl:
  enabled: true
  output_dir: /
  arb_dir: /
