name: app_shared
description: 'The "app_shared" package with shared code across all apps in monorepository'
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Dart.
  collection:
  # Internal.
  l:
  # Platform-dependant (Plugins).
  window_manager:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
